In [1]:
import pandas as pd

In [40]:
df2016=pd.read_csv('2016weather.csv')
df2017 = pd.read_csv('2017_weather.csv')
df=pd.concat([df2016,df2017])

In [41]:
print(df2016.shape, df2017.shape)

(10382, 17) (5531, 17)

In [42]:
df.head(2)

,Unnamed: 0,Conditions,Date,Dew Point,Events,Gust Speed,Heat Index,Humidity,Precip,Pressure,Temp.,Time (EDT),Time (EST),Visibility,Wind Dir,Wind Speed,Windchill
0,0,Overcast,"Jan. 01, 2016",25.0 °F,NaN,-,NaN,51%,NaN,30.06 in,42.1 °F,NaN,12:51 AM,10.0 mi,Variable,4.6 mph,39.2 °F
1,1,Overcast,"Jan. 01, 2016",25.0 °F,NaN,-,NaN,53%,NaN,30.06 in,41.0 °F,NaN,1:51 AM,10.0 mi,Variable,3.5 mph,39.0 °F

In [43]:
df['Time (EDT)']=df['Time (EDT)'].fillna('')
df['Time (EST)']=df['Time (EST)'].fillna('')
df['Time']=df['Time (EDT)']+df['Time (EST)']

In [44]:
df.columns

Index(['Unnamed: 0', 'Conditions', 'Date', 'Dew Point', 'Events', 'Gust Speed',
       'Heat Index', 'Humidity', 'Precip', 'Pressure', 'Temp.', 'Time (EDT)',
       'Time (EST)', 'Visibility', 'Wind Dir', 'Wind Speed', 'Windchill',
       'Time'],
      dtype='object')

In [45]:
df=df[['Conditions','Date','Temp.','Time','Visibility','Wind Speed','Humidity']]

In [46]:
df['vis']=pd.to_numeric(df['Visibility'].astype(str).str[:-3],errors='coerce')      # make columns numeric
df['temp']=pd.to_numeric(df['Temp.'].astype(str).str[:-3],errors='coerce')
df['wind_speed']=pd.to_numeric(df['Wind Speed'].astype(str).str[:-4],errors='coerce')
df['humidity']=pd.to_numeric(df['Humidity'].astype(str).str[:-1],errors='coerce')

df.head(20)

,Conditions,Date,Temp.,Time,Visibility,Wind Speed,Humidity,vis,temp,wind_speed,humidity
0,Overcast,"Jan. 01, 2016",42.1 °F,12:51 AM,10.0 mi,4.6 mph,51%,10.0,42.1,4.6,51.0
1,Overcast,"Jan. 01, 2016",41.0 °F,1:51 AM,10.0 mi,3.5 mph,53%,10.0,41.0,3.5,53.0
2,Overcast,"Jan. 01, 2016",41.0 °F,2:51 AM,10.0 mi,4.6 mph,55%,10.0,41.0,4.6,55.0
3,Overcast,"Jan. 01, 2016",41.0 °F,3:51 AM,10.0 mi,9.2 mph,55%,10.0,41.0,9.2,55.0
4,Overcast,"Jan. 01, 2016",39.9 °F,4:51 AM,10.0 mi,10.4 mph,58%,10.0,39.9,10.4,58.0
5,Overcast,"Jan. 01, 2016",39.9 °F,5:51 AM,10.0 mi,6.9 mph,58%,10.0,39.9,6.9,58.0
6,Overcast,"Jan. 01, 2016",39.0 °F,6:51 AM,10.0 mi,Calm,60%,10.0,39.0,NaN,60.0
7,Overcast,"Jan. 01, 2016",39.0 °F,7:51 AM,10.0 mi,6.9 mph,57%,10.0,39.0,6.9,57.0
8,Partly Cloudy,"Jan. 01, 2016",39.0 °F,8:51 AM,10.0 mi,6.9 mph,55%,10.0,39.0,6.9,55.0
9,Overcast,"Jan. 01, 2016",39.9 °F,9:51 AM,10.0 mi,4.6 mph,55%,10.0,39.9,4.6,55.0
10,Overcast,"Jan. 01, 2016",39.9 °F,10:51 AM,10.0 mi,5.8 mph,53%,10.0,39.9,5.8,53.0
11,Overcast,"Jan. 01, 2016",39.9 °F,11:51 AM,10.0 mi,9.2 mph,51%,10.0,39.9,9.2,51.0
12,Overcast,"Jan. 01, 2016",39.9 °F,12:51 PM,10.0 mi,13.8 mph,51%,10.0,39.9,13.8,51.0
13,Overcast,"Jan. 01, 2016",39.9 °F,1:51 PM,10.0 mi,6.9 mph,51%,10.0,39.9,6.9,51.0
14,Overcast,"Jan. 01, 2016",39.0 °F,2:51 PM,10.0 mi,11.5 mph,49%,10.0,39.0,11.5,49.0
15,Overcast,"Jan. 01, 2016",39.0 °F,3:51 PM,10.0 mi,-,46%,10.0,39.0,NaN,46.0
16,Clear,"Jan. 01, 2016",37.9 °F,4:51 PM,10.0 mi,11.5 mph,48%,10.0,37.9,11.5,48.0
17,Clear,"Jan. 01, 2016",37.9 °F,5:51 PM,10.0 mi,8.1 mph,48%,10.0,37.9,8.1,48.0
18,Partly Cloudy,"Jan. 01, 2016",37.0 °F,6:51 PM,10.0 mi,12.7 mph,50%,10.0,37.0,12.7,50.0
19,Clear,"Jan. 01, 2016",37.0 °F,7:51 PM,10.0 mi,9.2 mph,48%,10.0,37.0,9.2,48.0

In [47]:
df['datetime'] = df["Date"].map(str) + " " + df["Time"]         # create one-hour datetime column
df['datetime'] = pd.to_datetime(df['datetime'])
#weather.assign(rounded_dt=weather.datetime.dt.round('H'))
df['datetime']=pd.to_datetime(df.datetime.dt.date) + pd.to_timedelta(df.datetime.dt.hour, unit='H')
df.head()

,Conditions,Date,Temp.,Time,Visibility,Wind Speed,Humidity,vis,temp,wind_speed,humidity,datetime
0,Overcast,"Jan. 01, 2016",42.1 °F,12:51 AM,10.0 mi,4.6 mph,51%,10.0,42.1,4.6,51.0,2016-01-01 00:00:00
1,Overcast,"Jan. 01, 2016",41.0 °F,1:51 AM,10.0 mi,3.5 mph,53%,10.0,41.0,3.5,53.0,2016-01-01 01:00:00
2,Overcast,"Jan. 01, 2016",41.0 °F,2:51 AM,10.0 mi,4.6 mph,55%,10.0,41.0,4.6,55.0,2016-01-01 02:00:00
3,Overcast,"Jan. 01, 2016",41.0 °F,3:51 AM,10.0 mi,9.2 mph,55%,10.0,41.0,9.2,55.0,2016-01-01 03:00:00
4,Overcast,"Jan. 01, 2016",39.9 °F,4:51 AM,10.0 mi,10.4 mph,58%,10.0,39.9,10.4,58.0,2016-01-01 04:00:00

In [48]:
df.isnull().sum()

Conditions       0
Date             0
Temp.            0
Time             0
Visibility       0
Wind Speed       0
Humidity         0
vis            248
temp             8
wind_speed    3670
humidity         8
datetime         0
dtype: int64

In [60]:
df=df[['datetime','Conditions','vis','humidity','temp','wind_speed']]
df.wind_speed.fillna(method='ffill',inplace=True)       # fill NAs with last value
df.vis.fillna(method='ffill',inplace=True)              # fill NAs with last value
df.head()

             datetime Conditions   vis  humidity  temp  wind_speed
0 2016-01-01 00:00:00   Overcast  10.0      51.0  42.1         4.6
1 2016-01-01 01:00:00   Overcast  10.0      53.0  41.0         3.5
2 2016-01-01 02:00:00   Overcast  10.0      55.0  41.0         4.6
3 2016-01-01 03:00:00   Overcast  10.0      55.0  41.0         9.2
4 2016-01-01 04:00:00   Overcast  10.0      58.0  39.9        10.4

In [55]:
print('Percentage of rows that are duplicated: ',df.duplicated(subset='datetime').sum()/df.shape[0]*100)

Percentage of rows that are duplicated:  17.6019606611

In [59]:
df.drop_duplicates(subset='datetime',keep='first',inplace=True)
print('Percentage of rows that are duplicated: ',df.duplicated(subset='datetime').sum()/df.shape[0]*100)

Percentage of rows that are duplicated:  0.0

In [83]:
#df=df.set_index('datetime')
start_2016='2016-04-01 00:00:00'
end_2016='2016-04-30 23:00:00'
start_2017='2017-04-01 00:00:00'
end_2017='2017-04-30 23:00:00'

df2016=df[start_2016:end_2016]
df2017=df[start_2017:end_2017]

df_final=pd.concat([df2016,df2017])
print("Expected shape (30*24*2): ",30*24*2)
print("Shape: ",df_final.shape)

Expected shape (30*24*2):  1440
Shape:  (1419, 5)

In [84]:
df_final.head(2)

                        Conditions   vis  humidity  temp  wind_speed
datetime
2016-04-01 00:00:00  Mostly Cloudy  10.0      75.0  64.0         4.6
2016-04-01 01:00:00       Overcast  10.0      75.0  64.9         6.9

In [85]:
weather_dummy = pd.get_dummies(df_final.Conditions,prefix = '',prefix_sep='')
df_final = df_final.merge(weather_dummy, right_index = True, left_index  = True, how = 'outer')
df_final.describe()    
# Note last column if 'unknown' which is 1 for just five rows

,vis,humidity,temp,wind_speed,Clear,Haze,Heavy Rain,Light Rain,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Unknown
count,1419.000000,1414.000000,1414.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000,1419.000000
mean,9.145314,55.650636,54.499081,6.783791,0.513742,0.009866,0.001409,0.049331,0.000705,0.052854,0.295278,0.037350,0.008457,0.027484,0.003524
std,2.117536,22.551277,10.403978,4.776274,0.499987,0.098872,0.037529,0.216634,0.026547,0.223821,0.456329,0.189685,0.091603,0.163547,0.059276
min,0.800000,9.000000,27.000000,3.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,37.000000,48.000000,4.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10.000000,53.000000,53.100000,5.800000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10.000000,73.000000,61.000000,8.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,10.000000,100.000000,84.900000,85.200000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [88]:
df_final.Unknown.sum()

5

In [89]:
df_final

,Conditions,vis,humidity,temp,wind_speed,Clear,Haze,Heavy Rain,Light Rain,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Unknown
datetime,,,,,,,,,,,,,,,,
2016-04-01 00:00:00,Mostly Cloudy,10.0,75.0,64.0,4.6,0,0,0,0,0,1,0,0,0,0,0
2016-04-01 01:00:00,Overcast,10.0,75.0,64.9,6.9,0,0,0,0,0,0,1,0,0,0,0
2016-04-01 02:00:00,Overcast,10.0,73.0,66.0,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-01 03:00:00,Overcast,10.0,75.0,66.0,4.6,0,0,0,0,0,0,1,0,0,0,0
2016-04-01 04:00:00,Overcast,10.0,73.0,66.9,6.9,0,0,0,0,0,0,1,0,0,0,0
2016-04-01 05:00:00,Mostly Cloudy,10.0,75.0,66.0,4.6,0,0,0,0,0,1,0,0,0,0,0
2016-04-01 13:00:00,Scattered Clouds,10.0,61.0,72.0,5.8,0,0,0,0,0,0,0,0,0,1,0
2016-04-01 14:00:00,Scattered Clouds,10.0,53.0,75.0,11.5,0,0,0,0,0,0,0,0,0,1,0
2016-04-01 15:00:00,Clear,10.0,46.0,78.1,10.4,1,0,0,0,0,0,0,0,0,0,0
2016-04-01 16:00:00,Partly Cloudy,10.0,45.0,78.1,8.1,0,0,0,0,0,0,0,1,0,0,0
2016-04-01 17:00:00,Partly Cloudy,10.0,45.0,77.0,6.9,0,0,0,0,0,0,0,1,0,0,0
2016-04-01 18:00:00,Light Rain,8.0,59.0,71.1,6.9,0,0,0,1,0,0,0,0,0,0,0
2016-04-01 19:00:00,Mostly Cloudy,10.0,75.0,66.0,3.5,0,0,0,0,0,1,0,0,0,0,0
2016-04-01 20:00:00,Overcast,10.0,65.0,69.1,4.6,0,0,0,0,0,0,1,0,0,0,0
2016-04-01 21:00:00,Scattered Clouds,10.0,63.0,69.1,3.5,0,0,0,0,0,0,0,0,0,1,0
2016-04-01 22:00:00,Mostly Cloudy,10.0,49.0,69.8,3.5,0,0,0,0,0,1,0,0,0,0,0
2016-04-01 23:00:00,Mostly Cloudy,10.0,50.0,62.1,3.5,0,0,0,0,0,1,0,0,0,0,0
2016-04-02 00:00:00,Mostly Cloudy,10.0,50.0,61.0,3.5,0,0,0,0,0,1,0,0,0,0,0
2016-04-02 01:00:00,Mostly Cloudy,10.0,47.0,60.1,5.8,0,0,0,0,0,1,0,0,0,0,0
2016-04-02 02:00:00,Light Rain,10.0,56.0,57.9,5.8,0,0,0,1,0,0,0,0,0,0,0
2016-04-02 03:00:00,Overcast,10.0,60.0,55.9,4.6,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 04:00:00,Overcast,10.0,69.0,54.0,6.9,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 05:00:00,Overcast,10.0,69.0,54.0,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 07:00:00,Overcast,10.0,66.0,54.0,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 08:00:00,Overcast,10.0,69.0,54.0,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 09:00:00,Light Rain,4.0,80.0,50.0,5.8,0,0,0,1,0,0,0,0,0,0,0
2016-04-02 10:00:00,Light Rain,4.0,80.0,48.9,5.8,0,0,0,1,0,0,0,0,0,0,0
2016-04-02 11:00:00,Overcast,10.0,80.0,51.1,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 12:00:00,Overcast,10.0,71.0,51.1,5.8,0,0,0,0,0,0,1,0,0,0,0
2016-04-02 13:00:00,Overcast,10.0,59.0,52.0,5.8,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-04-29 18:00:00,Clear,10.0,45.0,80.1,3.5,1,0,0,0,0,0,0,0,0,0,0
2017-04-29 19:00:00,Clear,10.0,47.0,79.0,9.2,1,0,0,0,0,0,0,0,0,0,0
2017-04-29 20:00:00,Clear,10.0,50.0,77.0,4.6,1,0,0,0,0,0,0,0,0,0,0
2017-04-29 21:00:00,Overcast,10.0,53.0,75.0,4.6,0,0,0,0,0,0,1,0,0,0,0
2017-04-29 22:00:00,Overcast,10.0,57.0,72.0,3.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-29 23:00:00,Overcast,10.0,58.0,69.1,5.8,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 00:00:00,Overcast,10.0,56.0,68.0,4.6,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 01:00:00,Overcast,10.0,52.0,66.0,3.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 02:00:00,Overcast,10.0,47.0,64.9,4.6,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 03:00:00,Clear,10.0,46.0,64.0,3.5,1,0,0,0,0,0,0,0,0,0,0
2017-04-30 04:00:00,Scattered Clouds,10.0,52.0,63.0,8.1,0,0,0,0,0,0,0,0,0,1,0
2017-04-30 05:00:00,Scattered Clouds,10.0,54.0,61.0,4.6,0,0,0,0,0,0,0,0,0,1,0
2017-04-30 06:00:00,Overcast,10.0,44.0,59.0,10.4,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 07:00:00,Overcast,10.0,46.0,59.0,6.9,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 08:00:00,Mostly Cloudy,10.0,44.0,60.1,6.9,0,0,0,0,0,1,0,0,0,0,0
2017-04-30 09:00:00,Mostly Cloudy,10.0,46.0,59.0,8.1,0,0,0,0,0,1,0,0,0,0,0
2017-04-30 10:00:00,Overcast,10.0,46.0,61.0,8.1,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 11:00:00,Overcast,10.0,45.0,64.0,3.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 12:00:00,Overcast,10.0,48.0,62.1,9.2,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 13:00:00,Overcast,10.0,49.0,59.0,11.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 14:00:00,Overcast,10.0,49.0,57.9,5.8,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 15:00:00,Overcast,10.0,49.0,57.9,9.2,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 16:00:00,Overcast,10.0,53.0,57.0,4.6,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 17:00:00,Overcast,10.0,55.0,55.9,5.8,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 18:00:00,Overcast,10.0,59.0,55.0,5.8,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 19:00:00,Overcast,10.0,59.0,54.0,6.9,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 20:00:00,Overcast,10.0,57.0,54.0,3.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 21:00:00,Overcast,10.0,59.0,53.1,3.5,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 22:00:00,Overcast,10.0,64.0,53.1,6.9,0,0,0,0,0,0,1,0,0,0,0
2017-04-30 23:00:00,Overcast,10.0,69.0,53.1,8.1,0,0,0,0,0,0,1,0,0,0,0